export enum LINK_TYPE {
  FOLDER = 'FOLDER',
  NODE = 'NODE',
  PREVIEW = 'PREVIEW',
  DOCUMENT = 'DOCUMENT',
  SPREADSHEET = 'SPREADSHEET',
  NOTABLE = 'NOTABLE',
  MIND = 'MIND',
  UNKNOWN = 'UNKNOWN',
}
